### ISSUE TITLE
Issues with isWrongInstance()

### ISSUE THREAD

**Issue by spierce7** [square/mortar#112]
The comment on the isWrongInstance method in the example project's Activity is as follows: `Dev tools and the play store (and others?) launch with a different intent, and so lead to a redundant instance of this activity being spawned.`

I'm using Crashlytics to release the app to testers, so it allows the users to download and install the app. Once the app is installed they can launch the app from the Crashlytics app. What I'm seeing when I launch the app from Crashlytics is the Activity is evaluating that it's not the root, and then it immediately closes before anything can be seen. No `redundant` instance of the Activity is spawning, and so I'm left looking at the same screen I was looking at.

I wanted to ask what the implications were of me not using this method any more. Lets say that a redundant Activity is spawned. What's the worst case scenario here? I just want to better understand what's happening before I remove this check.

**Comment by rjrjr** [comment]
They way we've written this thing it could be important, since all activities in the same task will have the same name. If your Crashlytics-launched app is in the same task, when the first instance destroys its scope the second one will crash when it tries to inject something.

But it really depends on your app, and I think this one is more complicated than it needs to be. If you really have only one Activity, like this one, I suspect you should probably set its launchMode to `singleInstance`, or at least `singleTask`. What we did here was copy paste from a more complicated app of our own, before we had managed a simpler architecture. 

If you give that a try, could you reply with the result?

**Comment by rjrjr** [comment]
See also https://github.com/square/mortar/issues/87
