### ISSUE TITLE
ViewPresenter with getView() != null and scope.isDestroyed() == true

### ISSUE THREAD

**Issue by nathanielwolf** [square/mortar#93]
In a ViewPresenter, we post a runnable on the UI thread just after onLoad(). We have a check when this runnable executes to make sure we are still on the current screen. 
```java
if (getView() == null){
    return;
}
```

However, we are tracking crashes that occur because the user switches screens quickly and this runnable executes after the scope has been destroyed. This means getView() is not null while the scope bas been destroyed. This does not seem like it should be possible, but we did solved it by modifying our check at the beginning of the Runnable:
```java
if (getView() == null || scope.isDestroyed()){
    return;
}
```

**Comment by rjrjr** [comment]
Since this was filed ScreenConductor has been replaced by the SimplePathContainer in the Flow sample. You'll note that uses Animator instead of buggy old Animation. Animator's callbacks are reliable.

If you can possibly move from Animation to Animator it's well worth the time spent. If that's not an option, we worked around this problem by writing the name of a dying scope in a parent scope, and having that parent kill named scopes in its onload method — usually redundantly, which is safe, but it also catches dangling scopes left by this case.
