### ISSUE TITLE
Cache of view in Mortar

### ISSUE THREAD

**Issue by hijamoya** [square/mortar#95]
Hi, 
We use Mortar and Flow in our app. Currently, we want to speed up the view inflating between each screen, so we want to implement a cache of view. By doing so, we can avoid the inflating if we hit a cache of the view. However, we face some difficulty about dealing with life cycle of Mortar scope. I heard that you guys have implemented a cache in some apps. Could you give us some hints to help us? Any suggestion might be useful.
Many Thanks!

**Comment by lukaspili** [comment]
Would also be interested. Any plans on publishing some sample about that @loganj ?
Thanks!

**Comment by spierce7** [comment]
I'd also be interested.

**Comment by loganj** [comment]
It was done by the flow dispatcher, views were cached not in a mortar scope but in the dispatcher itself, and it turned out to be a pretty bad implementation. I'd gotten no noticeable performance improvement from it, though, so I threw it away rather than attempt to fix it.

Is inflating a view really your bottleneck? If so, it might be worth looking into why that view costs so much to create in the first place.
